import {
  Headphones,
  FileText,
  Youtube,
  MessageCircle,
  Newspaper,
  BookOpen,
  Tv,
  Briefcase,
  ArrowRight,
  Play,
  Lock,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  X,
  Menu,
  Sun,
  Moon,
  Search,
  Filter,
  Star,
  Mic,
  Repeat,
  Check,
  Pause,
  Diamond,
  Bell,
  Megaphone,
  GraduationCap,
  DollarSign,
  Users,
  Building2,
  Video,
  Edit,
  Upload,
  LogOut,
  Camera,
  User,
  Sparkles,
  Zap,
  Globe,
} from 'lucide-react'

export const Icons = {
  // Category icons
  headphones: Headphones,
  'file-text': FileText,
  youtube: Youtube,
  'message-circle': MessageCircle,
  newspaper: Newspaper,
  'book-open': BookOpen,
  tv: Tv,
  briefcase: Briefcase,

  // Navigation icons
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  x: X,
  menu: Menu,

  // Status icons
  play: Play,
  lock: Lock,
  checkCircle: CheckCircle,
  star: Star,

  // UI icons
  sun: Sun,
  moon: Moon,
  search: Search,
  filter: Filter,
  mic: Mic,
  repeat: Repeat,
  check: Check,
  pause: Pause,
  diamond: Diamond,
  bell: Bell,

  // Use Cases icons
  megaphone: Megaphone,
  graduationCap: GraduationCap,
  dollarSign: DollarSign,
  users: Users,
  building2: Building2,
  video: Video,
  edit: Edit,
  upload: Upload,
  logOut: LogOut,
  camera: Camera,
  user: User,
  sparkles: Sparkles,
  zap: Zap,
  globe: Globe,
}